name: vector_math
description: A Vector Math library for 2D and 3D applications.
version: 0.9.2
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/DartVectorMath
dependencies:
  unittest:
    sdk: any
