name: vector_math
version: 2.1.0-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/google/vector_math.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  benchmark_harness: any
  path: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.6.0
