name: vector_math
version: 1.4.4-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  benchmark_harness: any
  browser: any
  hop: '>=0.30.3 <0.32.0'
  hop_unittest: any
  unittest: '>=0.10.0 <0.12.0'
