name: vector_math
version: 1.4.4-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/google/vector_math.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  quiver: '>=0.19.0 <0.23.0'
dev_dependencies:
  benchmark_harness: any
  browser: any
  path: '>=1.0.0 <2.0.0'
  test: '>=0.12.0 <0.13.0'
